doctrine:
  dbal:
    driver: 'pdo_mysql'
    charset: utf8mb4
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_unicode_ci

    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.default
    auto_mapping: true
    mappings:
      DoctrineEntity:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Infrastructure/Database/DoctrineEntity'
        prefix: 'App\Infrastructure\Database\DoctrineEntity'
        alias: DoctrineEntity
