version: "3"

services:
  app:
    build: .
    container_name: ${APP_NAME}_app
    expose:
      - "9000"
    volumes:
      - .:/app
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./build/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app

  database:
    image: mariadb
    container_name: ${APP_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
