version: "3"

services:
  app:
    build: ./build/app/.
    container_name: symfony_app
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    links:
      - database
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./build/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
    depends_on:
      - app

  database:
    image: mysql:8
    container_name: symfony_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: symfony
    ports:
      - "3306:3306"
