parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/*'

  App\Application\Http\:
    resource: '../src/Application/Http'
    tags: ['controller.service_arguments']

  App\Application\Resolver\UuidValueResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 500 }
